name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        operating-systems: [ubuntu-latest]
        php-versions: ["8.0", "8.1"]
      fail-fast: false

    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-systems }}

    runs-on: ${{ matrix.operating-systems }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: PHPCS
        run: vendor/bin/phpcs

      - name: PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=2G

      - name: PHPUnit
        run: vendor/bin/phpunit
